apiVersion: v1
kind: Secret
metadata:
  labels:
    name: apim
  name: apim-secret
type: Opaque
data:
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  DATALAKE_SSL_KEY_PASS: {{ required "Please fill in datalakeKeyPass in values.yaml" .Values.secrets.datalakeKeyPass | b64enc | quote }}
  DSSG_SSL_KEY_PASS: {{ required "Please fill in dssgKeyPass in values.yaml" .Values.secrets.dssgKeyPass | b64enc | quote }}
  PAPI_PASSWORD: {{ .Values.user.papiPassword | b64enc | quote }}
  PAPI_USERNAME: {{ .Values.user.papiUsername | b64enc | quote }}
  PSSG_PASSWORD: {{ "M2NlY2RhZTMyZDZkNWMyZGI3" | b64enc | quote }}
  PSSG_SSL_KEY_PASS: {{ required "Please fill in pssgSslKeyPass in values.yaml" .Values.secrets.pssgSslKeyPass | b64enc | quote }}
  PSSG_USERNAME: {{ "admin" | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.config.password | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.config.username | b64enc | quote }}
  SSG_ADMIN_PASSWORD: {{ "M2NlY2RhZTMyZDZkNWMyZGI3" | b64enc }}
  SSG_ADMIN_USERNAME: {{ "admin" | b64enc }}
  SSG_PASSWORD: {{ "lh9M0SlIC8UHIBNwR/eQ5Z9V" | b64enc }}
  SSG_SSL_KEY_PASS: {{ required "Please fill in apimSslKeyPass in values.yaml" .Values.secrets.apimSslKeyPass | b64enc | quote }}
  SSG_USERNAME: {{ "admin" | b64enc }}
  DATALAKE_SSL_KEY: {{ include "apim-datalake" . | b64enc | b64enc | quote }}
  DSSG_SSL_KEY: {{ include "apim-dssg" . | b64enc | b64enc | quote }}
  PSSG_SSL_KEY: {{ include "pssg-ssl" . | b64enc | b64enc | quote }}
  SSG_SSL_KEY: {{ include "apim-ssl" . | b64enc | b64enc | quote }}
  APIM_SOLR_SSL_CERT: {{ include "apim-solr-crt" . | b64enc | b64enc | quote }}
  APIM_TPS_SSL_CERT: {{ include "apim-tps-crt" . | b64enc | b64enc | quote }}