apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: authenticator
  name: authenticator-config
data:
  CASSO_DEBUG_ENABLED: {{ required "Please fill in ssoDebug in values.yaml" .Values.user.ssoDebug | quote}}
  CASSO_ENABLED: "true"
  JAVA_OPTIONS: -Xms1024m -Xmx1024m
  NSS_SDB_USE_CACHE: "no"
  DATABASE_PORT: {{ include "database-port" . | quote }}
  DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.config.port | quote }}
  
  PORTAL_VERSION: {{ .Chart.AppVersion }}
