apiVersion: v1
data:
  CASSO_DEBUG_ENABLED: {{ required "Please fill in ssoDebug in values.yaml" .Values.user.ssoDebug | quote}}
  CASSO_ENABLED: "true"
  DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml"  .Values.user.databaseHost | quote }}
  DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | quote }}
  DATABASE_PORT: {{ include "database-port" . | quote }}
  DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | quote }}
  JAVA_OPTIONS: -Xms1024m -Xmx1024m
  NSS_SDB_USE_CACHE: "no"
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.config.password | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.config.port | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.config.username | quote }}
kind: ConfigMap
metadata:
  labels:
    name: authenticator
  name: authenticator-config