{{- if .Values.user.analyticsEnabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    name: coordinator
    service: coordinator
spec:
  clusterIP: None
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    name: coordinator
  sessionAffinity: ClientIP
{{- end -}}