{{- if .Values.user.analyticsEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: coordinator
  name: coordinator-secret
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ "minio"  | b64enc }}
  MINIO_SECRET_KEY: {{ "minio123" | b64enc }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
{{- end -}}