apiVersion: v1
kind: Secret
metadata:
  labels:
    name: dispatcher
  name: dispatcher-secret
type: Opaque
data:
  HTTPD_SSL_KEY: {{ include "dispatcher-ssl" . | b64enc | b64enc | quote }}
  HTTPD_SSL_KEY_PASS: {{ required "Please fill in dispatcherSslKeyPass in values.yaml" .Values.secrets.dispatcherSslKeyPass | b64enc | quote }}
