apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: dispatcher
  name: dispatcher-config
data:
  NSS_SDB_USE_CACHE: "no"
  PORTAL_SUBDOMAIN: {{ required "Please fill in domain in values.yaml" .Values.user.domain | quote }}
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  TSSG_PUBLIC_HOST: {{ include "tssg-public-host" . | quote }}
  USE_PROXY_PROTOCOL: "false"
