---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dispatcher
    service: dispatcher
  name: dispatcher
spec:
  ports:
    - port: 443
      targetPort: 8443
      name: portal-https
    - port: 9443
      targetPort: 9443
      name: pass-through
  selector:
    name: dispatcher
  type: ClusterIP
  sessionAffinity: ClientIP