{{- if .Values.user.analyticsEnabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: historical
  name: historical-config
data:
  SERVICE_NAME: historical
  ZOOKEEPER_HOST: zookeeper
  ZOOKEEPER_PORT: "2181"
  MINIO_URL: http://minio:9000
{{- end -}}