kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-role-binding
  labels:
    name: portal-job-role-binding
subjects:
- kind: ServiceAccount
  name: portal-service-account
roleRef:
  kind: Role
  name: job-role
  apiGroup: "rbac.authorization.k8s.io"