{{- if .Values.user.analyticsEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
    service: kafka
spec:
  clusterIP: None
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    name: kafka
{{- end -}}