{{- if .Values.user.analyticsEnabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: middlemanager
  name: middlemanager-config
data:
  SERVICE_NAME: middleManager
  ZOOKEEPER_HOST: zookeeper
  ZOOKEEPER_PORT: "2181"
  MINIO_URL: http://minio:9000
{{- end -}}