{{- if .Values.user.analyticsEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: middlemanager
  name: middlemanager-secret
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ "minio"  | b64enc }}
  MINIO_SECRET_KEY: {{ "minio123" | b64enc }}
{{- end -}}