---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: portal-enterprise
    service: portal-enterprise
  name: portal-enterprise
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: portal-enterprise-http
  selector:
    name: portal-enterprise
  type: ClusterIP
  sessionAffinity: ClientIP