apiVersion: v1
kind: Secret
metadata:
  name: portal-data-secret
labels:
    name: portal-data
type: Opaque
data:
  {{- if .Values.user.telemetry.telemetry_proxy_url }}
  TELEMETRY_PROXY_USERNAME: {{ .Values.user.telemetry.telemetry_proxy_username | b64enc | quote }}
  TELEMETRY_PROXY_PASSWORD: {{ .Values.user.telemetry.telemetry_proxy_password | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.setupInternalSMTP }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-internal-crt" . | b64enc | quote }}
  {{- else }}
  {{- if eq .Values.user.smtpCert "notinstalled" }}
  CONFIG_MAIL_SMTP_CERT: {{ required "Please fill in smtpCert in values.yaml" .Values.user.smtpCert| b64enc }}
    {{- else }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-external-crt" . | b64enc | quote }}
    {{- end}}
  {{- end}}
  CONFIG_MAIL_SMTP_PASSWORD: {{ required "Please fill in smtpPassword in values.yaml" .Values.user.smtpPassword | b64enc }}
  CONFIG_MAIL_SMTP_USERNAME: {{ required "Please fill in smtpUsername in values.yaml" .Values.user.smtpUsername | b64enc }}
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  GATEWAY_PK: {{ include "pssg-ssl" . | b64enc | b64enc | quote }}
  GATEWAY_PK_PASS: {{ required "Please fill in pssgSslKeyPass in values.yaml" .Values.secrets.pssgSslKeyPass | b64enc | quote }}
  GATEWAY_USERNAME: {{ "admin" | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.config.password | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.config.username | b64enc | quote }}
  RBAC_DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  RBAC_DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
