---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-enterprise
  labels:
    name: portal-enterprise
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{ .Values.portalEnterprise.replicaCount }}
  selector:
    matchLabels:
      name: portal-enterprise
  template:
    metadata:
      labels:
        name: portal-enterprise
    spec:
      serviceAccountName:  portal-service-account
      initContainers:
        - name: liquidbase-upgrade-portal
          image: "{{ .Values.image.portalRepository }}{{ .Values.image.upgradeVerify }}"
          args: ["job", 'db-upgrade']
        - name: liquidbase-upgrade-rbac
          image: "{{ .Values.image.portalRepository }}{{ .Values.image.upgradeVerify }}"
          args: ["job", 'rbac-upgrade']
      containers:
        - name: portal-enterprise
          image: "{{ .Values.image.portalRepository }}{{ .Values.image.enterprise }}"
          imagePullPolicy: "{{ .Values.portalEnterprise.image.pullPolicy }}"
          envFrom:
          - configMapRef:
              name: portal-enterprise-config
          readinessProbe:
            exec:
              command:
                - livenesscheck
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 15
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - livenesscheck
            initialDelaySeconds: 180
            timeoutSeconds: 1
            periodSeconds: 15
            successThreshold: 1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 2300Mi
            limits:
              cpu: 2000m
              memory: 3072Mi
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      - name: "{{ .Values.image.pullSecrets }}"
      {{- end }}
      dnsPolicy: "{{ .Values.portalEnterprise.dnsPolicy }}"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60