{{- if .Values.user.deployDatabase -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: portaldb
  name: portaldb-secret
type: Opaque
data:
  {{- if eq .Values.user.databaseType "postgresql" }}
  POSTGRES_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  POSTGRES_REPLICATION_MODE: {{ "master" | b64enc }}
  POSTGRES_REPLICATION_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  POSTGRES_REPLICATION_USER: {{ "repl" | b64enc }}
  POSTGRES_USER: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.user.databaseType "mysql" }}
  MYSQL_ROOT_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  MYSQL_USER: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  MYSQL_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  {{- end }}
{{- end -}}
