---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: portal-data
    service: portal-data
  name: portal-data
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: portal-data-http
  selector:
    name: portal-data
  type: ClusterIP
  sessionAffinity: ClientIP