apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: pssg
  name: pssg-config
data:
  BUSINESS_REPORTS_ENABLED: "false"
  CONFIG_APIM_HOST: {{ include "tssg-public-host" . | quote }}
  CONFIG_APIM_PORT: "443"
  CONFIG_BROKER_HOST: {{ include "broker-host" . | quote }}
  CONFIG_BROKER_PORT: "443"
  CONFIG_DSSG_DATALAKE_HOST: {{ include "analytics-host" . | quote }}
  CONFIG_DSSG_DATALAKE_PORT: "443"
  CONFIG_ENROLL_NOTIFICATION_EMAIL: {{ required "Please fill in enrollNotificationEmail in values.yaml"  .Values.user.enrollNotificationEmail }}
  CONFIG_MAIL_SMTP_HOST: {{ required "Please fill in smtpHost in values.yaml" .Values.user.smtpHost }}
  CONFIG_MAIL_SMTP_PORT: {{ required "Please fill in smtpPort in values.yaml" .Values.user.smtpPort | quote }}
  CONFIG_MAIL_SMTP_REQUIRE_SSL: {{ required "Please fill in smtpRequireSSL in values.yaml" .Values.user.smtpRequireSSL | quote }}
  CONFIG_PSSG_ENROLL_HOST: {{ include "pssg-enroll-host" . | quote }}
  CONFIG_PSSG_ENROLL_PORT: "443"
  CONFIG_PSSG_SSO_HOST: {{ include "pssg-sso-host" . | quote }}
  CONFIG_PSSG_SSO_PORT: "443"
  CONFIG_PSSG_SYNC_HOST: {{ include "pssg-sync-host" . | quote }}
  CONFIG_PSSG_SYNC_PORT: "443"
  DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  DATABASE_PORT: {{ include "database-port" . | quote }}
  DATABASE_TYPE: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseType | quote }}
  NSS_SDB_USE_CACHE: "no"
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  SSG_JVM_HEAP: 4096m
