apiVersion: v1
data:
  APIM_SSL_KEY: {{ include "apim-ssl" . | b64enc | quote }}
  APIM_SSL_KEY_PASS: {{ required "Please fill in apimSslKeyPass in values.yaml" .Values.secrets.apimSslKeyPass | quote }}
  BUSINESS_REPORTS_ENABLED: "false"
  CONFIG_APIM_HOST: {{ include "tssg-public-host" . | quote }}
  CONFIG_APIM_PORT: "443"
  CONFIG_BROKER_HOST: {{ include "broker-host" . | quote }}
  CONFIG_BROKER_PORT: "443"
  CONFIG_DSSG_DATALAKE_HOST: {{ include "analytics-host" . | quote }}
  CONFIG_DSSG_DATALAKE_PORT: "443"
  CONFIG_ENROLL_NOTIFICATION_EMAIL: {{ required "Please fill in enrollNotificationEmail in values.yaml"  .Values.user.enrollNotificationEmail }}
  {{- if .Values.user.setupInternalSMTP }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-internal-crt" . | b64enc | quote }}
  {{- else }}
    {{- if eq .Values.user.smtpCert "notinstalled" }}
  CONFIG_MAIL_SMTP_CERT: {{ required "Please fill in smtpCert in values.yaml" .Values.user.smtpCert }}
    {{- else }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-external-crt" . | b64enc | quote }}
    {{- end}}
  {{- end}}
  CONFIG_MAIL_SMTP_HOST: {{ required "Please fill in smtpHost in values.yaml" .Values.user.smtpHost }}
  CONFIG_MAIL_SMTP_PASSWORD: {{ required "Please fill in smtpPassword in values.yaml" .Values.user.smtpPassword }}
  CONFIG_MAIL_SMTP_PORT: {{ required "Please fill in smtpPort in values.yaml" .Values.user.smtpPort | quote }}
  CONFIG_MAIL_SMTP_REQUIRE_SSL: {{ required "Please fill in smtpRequireSSL in values.yaml" .Values.user.smtpRequireSSL | quote }}
  CONFIG_MAIL_SMTP_USERNAME: {{ required "Please fill in smtpUsername in values.yaml" .Values.user.smtpUsername }}
  CONFIG_PSSG_ENROLL_HOST: {{ include "pssg-enroll-host" . | quote }}
  CONFIG_PSSG_ENROLL_PORT: "443"
  CONFIG_PSSG_SSO_HOST: {{ include "pssg-sso-host" . | quote }}
  CONFIG_PSSG_SSO_PORT: "443"
  CONFIG_PSSG_SYNC_HOST: {{ include "pssg-sync-host" . | quote }}
  CONFIG_PSSG_SYNC_PORT: "443"
  DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | quote }}
  DATABASE_PORT: {{ include "database-port" . | quote }}
  DATABASE_TYPE: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseType | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | quote }}
  DATALAKE_SSL_KEY: {{ include "apim-datalake" . | b64enc | quote }}
  DATALAKE_SSL_KEY_PASS: {{ required "Please fill in datalakeKeyPass in values.yaml" .Values.secrets.datalakeKeyPass | quote }}
  DSSG_SSL_KEY: {{ include "apim-dssg" . | b64enc | quote }}
  DSSG_SSL_KEY_PASS: {{ required "Please fill in dssgKeyPass in values.yaml" .Values.secrets.dssgKeyPass | quote }}
  NSS_SDB_USE_CACHE: "no"
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  SSG_ADMIN_PASSWORD: M2NlY2RhZTMyZDZkNWMyZGI3
  SSG_ADMIN_USERNAME: admin
  SSG_JVM_HEAP: 4096m
  SSG_LICENSE: {{ include "portal-license" . | b64enc | quote }}
  SSG_SSL_KEY: {{ include "pssg-ssl" . | b64enc | quote }}
  SSG_SSL_KEY_PASS: {{ required "Please fill in pssgSslKeyPass in values.yaml" .Values.secrets.pssgSslKeyPass | quote }}
kind: ConfigMap
metadata:
  labels:
    name: pssg
  name: pssg-config