apiVersion: v1
kind: Secret
metadata:
  labels:
    name: pssg
  name: pssg-secret
type: Opaque
data:
  APIM_SSL_KEY_PASS: {{ required "Please fill in apimSslKeyPass in values.yaml" .Values.secrets.apimSslKeyPass | b64enc | quote }}
  {{- if .Values.user.setupInternalSMTP }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-internal-crt" . | b64enc | quote }}
  {{- else }}
    {{- if eq .Values.user.smtpCert "notinstalled" }}
  CONFIG_MAIL_SMTP_CERT: {{ required "Please fill in smtpCert in values.yaml" .Values.user.smtpCert | b64enc }}
    {{- else }}
  CONFIG_MAIL_SMTP_CERT: {{ include "smtp-external-crt" . | b64enc | quote }}
    {{- end}}
  {{- end}}
  CONFIG_MAIL_SMTP_PASSWORD: {{ required "Please fill in smtpPassword in values.yaml" .Values.user.smtpPassword | b64enc }}
  CONFIG_MAIL_SMTP_USERNAME: {{ required "Please fill in smtpUsername in values.yaml" .Values.user.smtpUsername | b64enc }}
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  DATALAKE_SSL_KEY_PASS: {{ required "Please fill in datalakeKeyPass in values.yaml" .Values.secrets.datalakeKeyPass | b64enc | quote }}
  DSSG_SSL_KEY_PASS: {{ required "Please fill in dssgKeyPass in values.yaml" .Values.secrets.dssgKeyPass | b64enc | quote }}
  SSG_ADMIN_PASSWORD: {{ "M2NlY2RhZTMyZDZkNWMyZGI3" | b64enc }}
  SSG_ADMIN_USERNAME: {{ "admin" | b64enc }}
  SSG_SSL_KEY_PASS: {{ required "Please fill in pssgSslKeyPass in values.yaml" .Values.secrets.pssgSslKeyPass | b64enc | quote }}
  APIM_SSL_KEY: {{ include "apim-ssl" . | b64enc | b64enc | quote }}
  DSSG_SSL_KEY: {{ include "apim-dssg" . | b64enc | b64enc | quote }}
  DATALAKE_SSL_KEY: {{ include "apim-datalake" . | b64enc | b64enc | quote }}
  SSG_SSL_KEY: {{ include "pssg-ssl" . | b64enc | b64enc | quote }}