---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
    service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - port: 4369
      targetPort: 4369
      name: 4369-rabbitmq
    - port: 5671
      targetPort: 5671
      name: 5671-rabbitmq
    - port: 5672
      targetPort: 5672
      name: 5672-rabbitmq
    - port: 1883
      targetPort: 1883
      name: 1883-rabbitmq
    - port: 15672
      targetPort: 15672
      name: 15672-rabbitmq
    - port: 25672
      targetPort: 25672
      name: 25672-rabbitmq
  selector:
    name: rabbitmq
  type: ClusterIP
  sessionAffinity: ClientIP