{{- if .Values.user.setupInternalSMTP -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: smtp
    service: smtp
  name: smtp
spec:
  ports:
    - port: 25
      targetPort: 25
      name: smtp
  selector:
    name: smtp
  type: ClusterIP
  sessionAffinity: ClientIP
{{- end -}}