apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: tenant_provisioner
  name: tenant-provisioner-config
data:
  APIM_GATEWAY_HOSTNAME: {{ include "tssg-public-host" . | quote }}
  APIM_GATEWAY_PORT: "9443"
  APIM_GATEWAY_TENANTID:  {{ include "default-tenant-id" . | quote }}
  APIM_PORTAL_SUBDOMAIN: {{ required "Please fill in domain in values.yaml" .Values.user.domain }}
  BUSINESS_REPORTS_ENABLED: "false"
  DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  DATABASE_NAME: {{ include "tps-db-name" . | quote }}
  DATABASE_PORT: {{ include "database-port" . | quote }}
  DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  JAVA_OPTS: -Xms512m -Xmx512m
  NSS_SDB_USE_CACHE: "no"
  OTK_PORT: "9443"
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  PORTAL_DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.config.port | quote }}