apiVersion: v1
kind: Secret
metadata:
  labels:
    name: tenant_provisioner
  name: tenant-provisioner-secret
type: Opaque
data:
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | b64enc | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | b64enc | quote }}
  GATEWAY_PASSWORD: {{ "M2NlY2RhZTMyZDZkNWMyZGI3" | b64enc }}
  GATEWAY_USERNAME: {{ "admin" | b64enc }}
  PAPI_USERNAME: {{ .Values.user.papiUsername | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.config.password | b64enc | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.config.username | b64enc | quote }}
  TPS_SSL_KEY_PASS: {{ required "Please fill in tpsKeyPass in values.yaml" .Values.secrets.tpsKeyPass | b64enc | quote }}
  TPS_SSL_KEY: {{ include "tps-key" . | b64enc | quote }}
  TPS_SSL_CERT: {{ include "tps-crt" . | b64enc | quote }}